---
name: NPM Check Versions

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  npm-outdated:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
      - name: Check outdated dependencies
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          if npx npm-check-updates | tee -a /dev/stderr | grep -q -e '→' ; then
            exit 1
          fi
